# .github/workflows/extract_transform.yml
name: ETL - Extract & Transform

on:
  schedule:
    - cron: '0 3 * * *'        # 00:00 BRT
  workflow_dispatch:          # permite disparo manual

jobs:
  extract_transform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pandas sqlalchemy psycopg2-binary requests python-dotenv

      # ==== Passo de DEBUG ====
      - name: Debug — listar estrutura de diretórios
        run: |
          echo "PWD: $(pwd)"
          ls -R .

      - name: Executar Extract
        run: python scripts/extract.py

      - name: Executar Transform
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python scripts/transform.py
