# .github/workflows/extract_transform.yml
name: ETL - Extract & Transform

# Agenda: 03:00 UTC todo dia = 00:00 BRT
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:   # permite disparo manual

jobs:
  extract_transform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install pandas sqlalchemy psycopg2-binary requests python-dotenv

    - name: Executar Extract
      run: |
        python scripts/extract.py

    - name: Executar Transform
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        python scripts/transform.py
