name: ETL - Extract & Transform

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  extract_transform:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Vinicios@212121
          POSTGRES_DB: ecommerce_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="PGPASSWORD='Vinicios@212121' pg_isready -U postgres -d ecommerce_db"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgresql://postgres:Vinicios%40212121@localhost:5432/ecommerce_db

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pandas sqlalchemy psycopg2-binary requests python-dotenv

      - name: Esperar Postgres ficar pronto
        run: |
          echo "Aguardando o PostgreSQL iniciar…"
          until PGPASSWORD='Vinicios@212121' pg_isready -h localhost -p 5432 -U postgres; do
            sleep 1
          done

      - name: Criar schemas no Postgres
        run: |
          PGPASSWORD='Vinicios@212121' psql \
            -h localhost -U postgres -d ecommerce_db \
            -c "CREATE SCHEMA IF NOT EXISTS staging; CREATE SCHEMA IF NOT EXISTS analytics;"

      - name: Executar Extract
        run: python scripts/extract.py

      - name: Executar Transform
        run: python scripts/transform.py


