# .github/workflows/load_report.yml
name: ETL - Load & Report

# Agenda: 05:00 UTC todo dia = 02:00 BRT
on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  load_report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install pandas sqlalchemy psycopg2-binary matplotlib python-dotenv

    - name: Executar Load
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        python scripts/load.py

    - name: Executar Report
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        python scripts/report.py

    - name: Commit e Push dos resultados
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add data/processed/*.csv reports/*.png
        if ! git diff --cached --quiet; then
          git commit -m "Atualização automática: métricas e relatório"
          git push
        else
          echo "Sem mudanças nos outputs."
        fi
